In [7]:
# tf.random_uniform generates random values from uniform distribution
#within a range.

import tensorflow as tf
tf.compat.v1.disable_eager_execution() # need to disable eager in TF2.x

sess = tf.compat.v1.Session()

R1 = tf.compat.v1.random_uniform([2,3], minval=0, maxval=20)
print(sess.run(R1))


[[ 3.3039522 11.129231  12.456446 ]
 [14.460659  19.848629   8.295748 ]]


In [8]:
# tf.random_normal generates random values from the normal
# distribution having the specified mean and standard deviation.
R2 = tf.compat.v1.random_normal([2,3], mean=5, stddev=4)
print(sess.run(R2))

[[ 3.0872412  2.6587055  6.6784525]
 [ 3.7432685 10.753193   3.4737337]]


In [19]:
# tf.random_shuffle helps us to shuffle the values in the tensor each time
R3 = tf.compat.v1.random_shuffle(tf.compat.v1.diag([3,2,1]))
print(sess.run(R3))

[[3 0 0]
 [0 2 0]
 [0 0 1]]


In [25]:
# tf.crop
R4 = tf.compat.v1.random_crop(tf.compat.v1.diag([3,-2,1]), [3,2])
print(sess.run(R3))

[[0 0 1]
 [3 0 0]
 [0 2 0]]
