In [1]:
# tf.random_uniform generates random values from uniform distribution
#within a range.

import tensorflow as tf
tf.compat.v1.disable_eager_execution() # need to disable eager in TF2.x

sess = tf.compat.v1.Session()

R1 = tf.compat.v1.random_uniform([2,3], minval=0, maxval=20)
print(sess.run(R1))


[[ 3.2250142 14.447119  15.121284 ]
 [ 6.6844916 15.313656   5.935786 ]]


In [2]:
# tf.random_normal generates random values from the normal
# distribution having the specified mean and standard deviation.
R2 = tf.compat.v1.random_normal([2,3], mean=5, stddev=4)
print(sess.run(R2))

[[9.566173  4.011744  6.9189935]
 [4.9480066 5.389027  1.7451015]]


In [3]:
# tf.random_shuffle helps us to shuffle the values in the tensor each time
R3 = tf.compat.v1.random_shuffle(tf.compat.v1.diag([3,2,1]))
print(sess.run(R3))

[[0 2 0]
 [0 0 1]
 [3 0 0]]


In [4]:
# tf.crop
R4 = tf.compat.v1.random_crop(tf.compat.v1.diag([3,-2,1]), [3,2])
print(sess.run(R3))

[[0 2 0]
 [3 0 0]
 [0 0 1]]
