In [1]:
# ReLu and ELU
# ReLU (x) = max (0, x)
import tensorflow as tf
tf.compat.v1.disable_eager_execution() # need to disable eager in TF2.x
sess = tf.compat.v1.Session()

A = tf.compat.v1.nn.relu([-2, 1, -3, 13])
print(sess.run(A))

[ 0  1  0 13]


In [2]:
# ReLU6
# similar to ReLU only that the result cannot be more than 6 ever
B = tf.compat.v1.nn.relu6([-2,1,-3,13])
print(sess.run(B))

[0 1 0 6]


In [3]:
C = tf.compat.v1.nn.relu([[-2, 1, -3], [10, -16, -6]])
print(sess.run(C))

[[ 0  1  0]
 [10  0  0]]


In [4]:
# ELU (x) = e^x - 1 if x < 0
# ELU (x) = x if x>=0
D = tf.compat.v1.nn.elu([1.0, 2.0, 0, -2, -3])
print(sess.run(D))

[ 1.          2.          0.         -0.86466473 -0.95021296]


In [5]:
# softplus (x) = log(exp(x) +1)
E = tf.compat.v1.nn.softplus([1.0, 2, 0])
print(sess.run(E))

[1.3132616 2.126928  0.6931472]


In [6]:
# softsign computes  features/(abs(features) + 1)
F = tf.compat.v1.nn.softsign([1.0, 2, 0, 10])
print(sess.run(F))

[0.5        0.6666667  0.         0.90909094]
